# Generated by Django 4.1.3 on 2022-11-28 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoFoundingRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("low", models.IntegerField()),
                ("high", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FoundingRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("low", models.IntegerField()),
                ("high", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="OrganizerLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo", models.CharField(max_length=512)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.organizerlevel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("founding_type", models.CharField(max_length=1024)),
                ("submission_deadline", models.DateField()),
                ("consideration_period", models.CharField(max_length=255)),
                ("realisation_period", models.CharField(max_length=255)),
                ("result", models.TextField()),
                ("site", models.CharField(max_length=512)),
                ("document", models.CharField(max_length=512)),
                ("internal_contacts", models.CharField(max_length=512)),
                ("trl", models.IntegerField()),
                (
                    "co_founding_range",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.cofoundingrange",
                    ),
                ),
                (
                    "competitors",
                    models.ManyToManyField(
                        related_name="event",
                        related_query_name="event",
                        to="events.competitor",
                    ),
                ),
                (
                    "founding_range",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.foundingrange",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.organizer",
                    ),
                ),
                (
                    "precursor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.event",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        related_name="event",
                        related_query_name="event",
                        to="events.subject",
                    ),
                ),
            ],
        ),
    ]
