# Generated by Django 4.1.3 on 2022-12-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_foundingtype_remove_event_founding_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitor",
            name="code",
            field=models.IntegerField(default=0),
        ),
    ]
