# Generated by Django 4.1.3 on 2022-11-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_organizer_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="precursor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="logo",
            field=models.TextField(),
        ),
    ]
