# Generated by Django 4.1.3 on 2023-05-10 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_isfavoriteowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.event'),
        ),
        migrations.AlterField(
            model_name='favoritelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='IsFavoriteOwner',
        ),
    ]
