# Generated by Django 4.1.3 on 2023-05-10 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_alter_favoritelist_events_alter_favoritelist_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritelist',
            options={'verbose_name_plural': 'FavoriteLists'},
        ),
        migrations.AlterField(
            model_name='favoritelist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
